import { Unit } from "../index.ts"

export const USD = Unit.make("USD")
export const EUR = Unit.make("EUR")
export const GBP = Unit.make("GBP")
export const JPY = Unit.make("JPY")
export const CNY = Unit.make("CNY")
export const CHF = Unit.make("CHF")
export const AUD = Unit.make("AUD")
export const CAD = Unit.make("CAD")
export const SGD = Unit.make("SGD")
export const HKD = Unit.make("HKD")
export const INR = Unit.make("INR")
export const BRL = Unit.make("BRL")
export const KRW = Unit.make("KRW")
export const MXN = Unit.make("MXN")
export const TRY = Unit.make("TRY")
export const AED = Unit.make("AED")
export const NZD = Unit.make("NZD")
