/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as OgSplatRouteImport } from './routes/og.$'
import { Route as ArticlesSplatRouteImport } from './routes/articles.$'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgSplatRoute = OgSplatRouteImport.update({
  id: '/og/$',
  path: '/og/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSplatRoute = ArticlesSplatRouteImport.update({
  id: '/articles/$',
  path: '/articles/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/search': typeof SearchRoute
  '/articles/$': typeof ArticlesSplatRoute
  '/og/$': typeof OgSplatRoute
  '/articles/': typeof ArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/search': typeof SearchRoute
  '/articles/$': typeof ArticlesSplatRoute
  '/og/$': typeof OgSplatRoute
  '/articles': typeof ArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/search': typeof SearchRoute
  '/articles/$': typeof ArticlesSplatRoute
  '/og/$': typeof OgSplatRoute
  '/articles/': typeof ArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/llms-full.txt'
    | '/search'
    | '/articles/$'
    | '/og/$'
    | '/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/llms-full.txt'
    | '/search'
    | '/articles/$'
    | '/og/$'
    | '/articles'
  id:
    | '__root__'
    | '/$'
    | '/llms-full.txt'
    | '/search'
    | '/articles/$'
    | '/og/$'
    | '/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  SearchRoute: typeof SearchRoute
  ArticlesSplatRoute: typeof ArticlesSplatRoute
  OgSplatRoute: typeof OgSplatRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/$': {
      id: '/og/$'
      path: '/og/$'
      fullPath: '/og/$'
      preLoaderRoute: typeof OgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$': {
      id: '/articles/$'
      path: '/articles/$'
      fullPath: '/articles/$'
      preLoaderRoute: typeof ArticlesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  SearchRoute: SearchRoute,
  ArticlesSplatRoute: ArticlesSplatRoute,
  OgSplatRoute: OgSplatRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
