name: Check

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: useblacksmith/checkout@v1
      - uses: ./.github/actions/checkout-crosshatch
      - uses: ./konfik/configure-environment
      - run: pnpm format --check
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test
        env:
          CDP_API_KEY_ID: ${{ vars.CDP_API_KEY_ID }}
          CDP_API_KEY_SECRET: ${{ secrets.CDP_API_KEY_SECRET }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
          EIP155_ADDRESS: ${{ vars.EIP155_ADDRESS }}
          SOLANA_ADDRESS: ${{ vars.SOLANA_ADDRESS }}
