# name: Deploy Docs
# on:
#   workflow_dispatch:
#   push:
#     branches: [main]
#   pull_request:
#     types: [opened, synchronize, reopened]

# permissions:
#   contents: read

# concurrency:
#   group: ${{ github.workflow }}

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     environment: docs.crosshatch.dev
#     if: >
#       github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' &&
#        github.event.pull_request.author_association != 'FIRST_TIMER' &&
#        github.event.pull_request.author_association != 'FIRST_TIME_CONTRIBUTOR' &&
#        github.event.pull_request.author_association != 'NONE')
#     steps:
#       - uses: actions/checkout@v6
#       - uses: ./konfik/.github/actions/configure_environment
#       - run: pnpm build
#       - run: pnpm build
#         working-directory: docs
#       - id: branch
#         run: |
#           if [ "${{ github.event_name }}" = "pull_request" ]; then
#             echo "name=${{ github.head_ref }}" >> "$GITHUB_OUTPUT"
#           else
#             echo "name=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
#           fi
#       - id: deploy
#         working-directory: docs
#         env:
#           CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#           CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
#         run: pnpm wrangler pages deploy dist --project-name=crosshatch-docs --branch=${{ steps.branch.outputs.name }}
