name: Deploy Crosshatch Chat

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: chat
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/configure_environment
      - run: pnpm build
      - run: pnpm build
        working-directory: examples/chat
      - run: pnpm dlx wrangler deploy
        working-directory: examples/chat
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
