# name: Deploy lmnl.im

# on:
#   workflow_dispatch:
#   push:
#     branches: [main]

# permissions:
#   contents: read

# concurrency:
#   group: ${{ github.workflow }}

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     environment: lmnl.im
#     steps:
#       - uses: actions/checkout@v6
#       - uses: ./repos/konfik/.github/actions/configure_environment
#       - run: pnpm build
#       - run: DEV=false pnpm build
#         working-directory: examples/lmnl.im/app
#       - run: pnpm wrangler deploy
#         working-directory: examples/lmnl.im/app
#         env:
#           CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#           CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
