name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}

jobs:
  alchemize:
    uses: crosshatch/konfik/.github/workflows/alchemize.yml@main
    with:
      cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
