name: Deploy Chat App

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - examples/chat/**
      - "@crosshatch/**"
      - crosshatch/**

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: chat_deployment
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/configure_environment
      - name: Build chat app
        run: pnpm --filter crosshatch.chat build
      - name: Deploy chat app
        working-directory: examples/chat
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: pnpm dlx wrangler deploy
