name: Checkout Crosshatch
description: Checkout Crosshatch and initialize the konfik submodule.
runs:
  using: composite
  steps:
    - shell: bash
      run: "git -c url.https://github.com/.insteadOf=git@github.com: submodule update --init --depth 1 -- konfik"
